url: "https://leboisdelagrenouille.github.io"
baseurl: ""

# Site settings
title: Le bois de la grenouille
email: leboisdelagrenouille@laposte.net
description: "Le site du bois de la grenouille"

#build-settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

prose:
  rooturl: ''
  siteurl: "https://leboisdelagrenouille.github.io"
  media: 'assets/img/posts'
  metadata:
    _posts:
      - name: "sur-titre"
        field:
          label: "Sur-titre du produit"
          element: "text"
          placeholder: "Apparait au-dessus du produit [facultatif]"
      - name: "titre"
        field:
          label: "Nom du produit"
          element: "text"
          placeholder: "Nom du produit"
      - name: "prix"
        field:
          label: "Prix"
          element: "text"
          placeholder: "Entrer le prix"
      - name: "description"
        field:
          label: "Text"
          element: "textarea"
          placeholder: "Entrer la descrition du produit"
      - name: "categorie"
        field:
          label: "Cat√©gorie"
          element: "select"
          options:
            - jeux
            - objets-deco
            - grands-jeux
      - name: "layout"
        field:
          element: "hidden"
          value: "produit"